CREATE DATABASE [学生选课]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'学生选课', FILENAME = N'D:\FuckingDATA\学生选课.mdf' , SIZE = 8192KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'学生选课_log', FILENAME = N'D:\FuckingDATA\学生选课_log.ldf' , SIZE = 8192KB , MAXSIZE = 1048576KB , FILEGROWTH = 10%)
ALTER DATABASE [学生选课] ADD FILEGROUP [选课1]
ALTER DATABASE [学生选课] ADD FILEGROUP [选课2]
