@startuml RequestOn

participant c as "c: Customer" order 1

participant cc as "cc: CustomerController" order 2

participant s as "s: Service" order 4

participant db as "dbFacade: DBFacade" order 5

participant m as "m: RequestOnMapper" order 6

participant i as "inWaitRequest" order 7

participant w as "inWaitList: list<Request>" order 8

c -> cc: 1. RequestOn(RoomID, CurrentRoomTemp)

activate cc

alt RequestNumber <= MaxRequsetNumber
cc -> s: 2. <<create>>
s -> db: 3. insertRequestOn
activate db
db -> db: 4. getMapper
db -> m: 5. insert(RequestOn)
activate m
db <-- m: 6. Return(isOK)
deactivate m
s <-- db: 7. Return(isOK)
deactivate db

cc -> s: 8. update
activate s
cc <-- s: 9. Return(OK)
deactivate s
c <-- cc: 10. Return(Mode, TargetTemp, FeeRate, Fee)

else else

cc -> i: 11. <<create>>
cc -> i: 12. Update
activate i
cc <-- i: 13. Return(isOK)
deactivate i
cc -> w: 14. Add(inWait)
activate w
cc <-- w: 15. Return(isOK)
deactivate w

cc -> cc: 16. save
c <-- cc: 17. Return(State=.wait)

end

deactivate cc

@enduml